#!/bin/bash
set -e
# Cross-compiles Pokedex.app and packages it into an .ipa using a
# Linux-hosted clang + iOS 6.1 SDK (see .github/actions/setup-toolchain).
#
# This mirrors scripts/build.sh + the packaging half of scripts/install.sh,
# but runs entirely on the CI runner -- no SSH round-trip to a physical
# iPad, and no scripts/config.sh (that file only exists locally and is
# gitignored). Requires CLANG/LDID/SDK env vars (exported by
# setup-toolchain) and a src/data + src/sprites already generated by
# tools/fetch.php + tools/process.php.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$ROOT_DIR/src"
APP_NAME="Pokedex"

: "${CLANG:?CLANG env var must point at the cross clang binary}"
: "${LDID:?LDID env var must point at the ldid binary}"
: "${SDK:?SDK env var must point at the iPhoneOS SDK}"

VERSION=$(grep -A1 'CFBundleShortVersionString' "$SRC_DIR/Info.plist" | tail -1 | sed -E 's/.*<string>(.*)<\/string>.*/\1/')
echo "==> Building ${APP_NAME} v${VERSION}..."

cd "$SRC_DIR"
"$CLANG" -target armv7-apple-ios6.0 \
  -isysroot "$SDK" \
  -fobjc-arc \
  -framework UIKit \
  -framework Foundation \
  -framework CoreGraphics \
  -framework QuartzCore \
  -o "$APP_NAME" \
  $(ls *.m | grep -v '^EggGroup[CDLS]')

echo "==> Signing..."
"$LDID" -S "$APP_NAME"

echo "==> Packaging IPA..."
PAYLOAD_DIR="$ROOT_DIR/.ci-payload"
rm -rf "$PAYLOAD_DIR"
mkdir -p "$PAYLOAD_DIR/Payload/${APP_NAME}.app"
cp "$APP_NAME" "$PAYLOAD_DIR/Payload/${APP_NAME}.app/"
cp Info.plist "$PAYLOAD_DIR/Payload/${APP_NAME}.app/"
cp icons/*.png "$PAYLOAD_DIR/Payload/${APP_NAME}.app/" 2>/dev/null || true
cp -r data "$PAYLOAD_DIR/Payload/${APP_NAME}.app/"
cp -r sprites "$PAYLOAD_DIR/Payload/${APP_NAME}.app/"
rm -f "$APP_NAME"

mkdir -p "$ROOT_DIR/dist"
IPA_PATH="$ROOT_DIR/dist/${APP_NAME}-v${VERSION}.ipa"
rm -f "$IPA_PATH"
( cd "$PAYLOAD_DIR" && zip -qr "$IPA_PATH" Payload )
rm -rf "$PAYLOAD_DIR"

echo "==> Built $IPA_PATH"
if [ -n "$GITHUB_OUTPUT" ]; then
  echo "version=$VERSION" >> "$GITHUB_OUTPUT"
  echo "ipa_path=$IPA_PATH" >> "$GITHUB_OUTPUT"
fi
